# analyzer:
#   errors:
#     missing_required_param: warning
#     missing_return: warning

# linter:
#   rules:
#     - always_use_package_imports
#     - always_declare_return_types
#     - always_require_non_null_named_parameters
#     - annotate_overrides
#     - avoid_empty_else
#     - avoid_print
#     - avoid_positional_boolean_parameters
#     - avoid_relative_lib_imports
#     - avoid_slow_async_io
#     - avoid_returning_null
#     - avoid_types_as_parameter_names
#     - avoid_unused_constructor_parameters
#     - await_only_futures
#     - camel_case_types
#     - cancel_subscriptions
#     - close_sinks
#     - control_flow_in_finally
#     - empty_constructor_bodies
#     - empty_statements
#     - file_names
#     - invariant_booleans
#     - iterable_contains_unrelated_type
#     - library_names
#     - library_prefixes
#     - lines_longer_than_80_chars
#     - list_remove_unrelated_type
#     - literal_only_boolean_expressions
#     - no_duplicate_case_values
#     - no_logic_in_create_state
#     - non_constant_identifier_names
#     - prefer_asserts_in_initializer_lists
#     - prefer_collection_literals
#     - prefer_conditional_assignment
#     - prefer_const_constructors
#     - prefer_const_declarations
#     - prefer_const_literals_to_create_immutables
#     - prefer_contains
#     - prefer_equal_for_default_values
#     - prefer_final_fields
#     - prefer_final_locals
#     - prefer_foreach
#     - prefer_initializing_formals
#     - prefer_is_empty
#     - prefer_is_not_empty
#     - prefer_iterable_whereType
#     - prefer_single_quotes
#     - prefer_void_to_null
#     - recursive_getters
#     - unnecessary_brace_in_string_interps
#     - unnecessary_const
#     - unnecessary_new
#     - unnecessary_null_aware_assignments
#     - unnecessary_null_in_if_null_operators
#     - unnecessary_overrides
#     - unnecessary_parenthesis
#     - unnecessary_statements
#     - unnecessary_this
#     - valid_regexps
